kind: Service
apiVersion: v1
metadata:
  name: csi-gcs-controller
  namespace: kube-system
  labels:
    app: csi-gcs-controller
spec:
  selector:
    app: csi-gcs-controller
  ports:
    - name: dummy
      port: 12345
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: csi-gcs-controller
  namespace: kube-system
spec:
  serviceName: csi-gcs-controller
  replicas: 1
  selector:
    matchLabels:
      app: csi-gcs-controller
  template:
    metadata:
      labels:
        app: csi-gcs-controller
    spec:
      serviceAccount: csi-gcs-controller
      containers:
        - name: csi-provisioner
          image: quay.io/k8scsi/csi-provisioner:v1.6.0
          args:
            - "--csi-address=$(ADDRESS)"
            - "--extra-create-metadata"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
        - name: csi-resizer
          image: quay.io/k8scsi/csi-resizer:v0.2.0
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
        - name: csi-gcs-controller
          image: docker.io/ofekmeister/csi-gcs:latest
          imagePullPolicy: Always
          args:
          - "--node-name=$(KUBE_NODE_NAME)"
          # https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/logging.md
          - "--v=5"
          env:
          - name: KUBE_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          volumeMounts:
          - name: socket-dir
            mountPath: /csi
      volumes:
        - name: socket-dir
          emptyDir:
        - name: dockersock
          hostPath:
            path: /var/run/docker.sock
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry
            type: Directory
