apiVersion: storage.k8s.io/v1beta1
kind: CSIDriver
metadata:
  name: gcs.csi.ofek.dev
# https://kubernetes-csi.github.io/docs/csi-driver-object.html
spec:
  attachRequired: false
  podInfoOnMount: false