{{- if .Values.priorityClass.create }}
apiVersion: scheduling.k8s.io/v1
description: Priority class for the GCS driver
kind: PriorityClass
metadata:
  name: {{ include "csi-gcs.priorityClassName" . }}
preemptionPolicy: Never
value: 1000000
{{- end }}
