apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: publishedvolumes.{{ .Values.driverName }}
spec:
  group: {{ .Values.driverName }}
  versions:
    - name: v1beta1
      served: true
      storage: true
  preserveUnknownFields: false
  scope: Cluster
  names:
    plural: publishedvolumes
    singular: publishedvolume
    kind: PublishedVolume
  validation:
    openAPIV3Schema:
      type: object
      required:
        - spec
      properties:
        spec:
          type: object
          required:
            - node
            - targetPath
            - volumeHandle
            - options
            - pod
          properties:
            node:
              type: string
            targetPath:
              type: string
            volumeHandle:
              type: string
            options:
              type: object
              additionalProperties:
                type: string
            pod:
              type: object
              required:
               - name
               - namespace
              properties:
                name:
                  type: string
                namespace:
                  type: string
