apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../stable
images:
- name: quay.io/k8scsi/csi-node-driver-registrar
  newName: gcr.io/gke-release/csi-node-driver-registrar
  newTag: v1.2.0-gke.0
- name: quay.io/k8scsi/csi-provisioner
  newName: gcr.io/gke-release/csi-provisioner
  newTag: v1.6.0-gke.0
- name: quay.io/k8scsi/csi-resizer
  newName: gcr.io/gke-release/csi-resizer
  newTag: v0.2.0-gke.0
