name: Docs

on: [push, pull_request]

jobs:
  build:
    name: Build Docs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: "3.8"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install --upgrade -r requirements.txt

    - name: Build docs
      run: |
        invoke docs.build

    - uses: actions/upload-artifact@v1
      with:
        name: Docs
        path: site
