name: Documentation

on:
  push:
    paths:
    - docs/**
    - .github/workflows/publish.yml
    - tasks/docs.py
    - mkdocs.yml
    - tox.ini
    branches:
    - master

jobs:
  build:
    name: Build Docs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: "3.8"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install --upgrade -r requirements.txt

    - name: Build docs
      run: |
        invoke docs.build

    - uses: actions/upload-artifact@v1
      with:
        name: Documentation
        path: site

  publish:
    name: Publish Docs
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: Documentation
          path: site

      - name: Publish generated content to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
