name: Image

on: [push, pull_request]

jobs:
  build_container:
    name: Build Docker Container
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 50

    - name: Fetch Tags
      run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: "3.8"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install --upgrade -r requirements.txt

    - name: Build Docker Container
      run: |
        invoke image --release --compress

    - name: Package Container
      run: |
        TAG=$(git describe --long --tags --match='v*' --dirty)
        docker save -o ./container.tar.gz ofekmeister/csi-gcs:$TAG

    - uses: actions/upload-artifact@v1
      with:
        name: Container
        path: ./container.tar.gz

  publish_container:
    name: Publish Container
    runs-on: ubuntu-latest
    needs:
      - build_container
    # Only Publish Images from our repository, not for MR
    if: github.event_name == 'push'
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 50

    - name: Fetch Tags
      run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: "3.8"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install --upgrade -r requirements.txt

    - uses: actions/download-artifact@v1
      with:
        name: Container
        path: .

    - name: Import Container
      run:  |
        TAG=$(git describe --long --tags --match='v*' --dirty)
        docker import ./container.tar.gz ofekmeister/csi-gcs:$TAG

    - name: Login to Docker.io
      run: |
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      env:
        DOCKER_USERNAME: ${{ secrets.DockerUsername }}
        DOCKER_PASSWORD: ${{ secrets.DockerPassword }}

    - name: Publish Docker Container
      run: |
        invoke image.deploy
