name: Test

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: "3.8"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install --upgrade -r requirements.txt

    - name: Install Test Secrets
      shell: bash
      env:
        TEST_SECRETS: ${{ secrets.TestSecrets }}
      run: |
        echo "$TEST_SECRETS" > test/secret.yaml

    - name: Build image
      run: |
        invoke image

  docs:
    name: Generate Docs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: "3.8"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install --upgrade -r requirements.txt

    - name: Build docs
      run: |
        invoke docs.build

    - uses: actions/upload-artifact@v1
      with:
        name: Documentation
        path: site

  test_sanity:
    name: Sanity Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: "3.8"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install --upgrade -r requirements.txt

    - name: Install Test Secrets
      shell: bash
      env:
        TEST_SECRETS: ${{ secrets.TestSecrets }}
      run: |
        echo "$TEST_SECRETS" > test/secret.yaml

    - name: Sanity Test
      # TODO: Remove when Sanity Tests are fixed
      continue-on-error: true
      run: |
        invoke test.sanity
