name: Test

on: [push, pull_request]

jobs:
  test_unit:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13.3

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: "3.8"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install --upgrade -r requirements.txt

    - uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-test_unit-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-test_unit-
          ${{ runner.os }}-go-

    - name: Run Tests
      run: |
        invoke test.unit

  test_sanity:
    name: Test Sanity
    runs-on: ubuntu-latest
    # Secrets are only available for Push
    if: github.event_name == 'push'
    steps:
    - uses: actions/checkout@v2

    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13.3

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: "3.8"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install --upgrade -r requirements.txt

    - uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-test_sanity-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-test_sanity-
          ${{ runner.os }}-go-

    - name: Install Test Secrets
      shell: bash
      env:
        TEST_SECRETS: ${{ secrets.TestSecrets }}
      run: |
        echo "$TEST_SECRETS" > test/secret.yaml

    - name: Run Tests
      # TODO: Remove when Sanity Tests are fixed
      # https://github.com/ofek/csi-gcs/issues/15
      continue-on-error: true
      run: |
        invoke docker -c "invoke test.sanity"